
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi1.practice1.parse;

/** CUP generated class containing symbol constants. */
public class ParserCodigoSym {
  /* terminals */
  public static final int IDHEADER = 3;
  public static final int MULT = 14;
  public static final int HASH = 2;
  public static final int LISTPLUS = 8;
  public static final int EOF = 0;
  public static final int LISTORDERONE = 7;
  public static final int BOLD = 4;
  public static final int LISTORDEN = 6;
  public static final int ID = 15;
  public static final int error = 1;
  public static final int PRINT = 12;
  public static final int RPAREN = 11;
  public static final int LPAREN = 10;
  public static final int BOLDITALIC = 5;
  public static final int WORD = 13;
  public static final int PARAGRAPH = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HASH",
  "IDHEADER",
  "BOLD",
  "BOLDITALIC",
  "LISTORDEN",
  "LISTORDERONE",
  "LISTPLUS",
  "PARAGRAPH",
  "LPAREN",
  "RPAREN",
  "PRINT",
  "WORD",
  "MULT",
  "ID"
  };
}

