
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi1.practice1.parse;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int PLOT = 4;
  public static final int WORD = 15;
  public static final int PLUS = 7;
  public static final int RPAREN = 13;
  public static final int POW = 11;
  public static final int LPAREN = 12;
  public static final int ID = 2;
  public static final int NUM = 16;
  public static final int EQUALS = 3;
  public static final int OPERADORES = 6;
  public static final int COMMA = 5;
  public static final int EOF = 0;
  public static final int MULT = 9;
  public static final int DIV = 10;
  public static final int MINUS = 8;
  public static final int DOT = 18;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int REPORTES = 19;
  public static final int FORMAT = 17;
  public static final int ERRORES = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "EQUALS",
  "PLOT",
  "COMMA",
  "OPERADORES",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POW",
  "LPAREN",
  "RPAREN",
  "PRINT",
  "WORD",
  "NUM",
  "FORMAT",
  "DOT",
  "REPORTES",
  "ERRORES"
  };
}

